__author__ = 'kruthar'
'''
Circular Figurate Numbers
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:

Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Square	 	    P4,n=n2	 	        1, 4, 9, 16, 25, ...
Pentagonal	 	P5,n=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	P6,n=n(2n-1)	 	1, 6, 15, 28, 45, ...
Heptagonal	 	P7,n=n(5n-3)/2	 	1, 7, 18, 34, 55, ...
Octagonal	 	P8,n=n(3n-2)	 	1, 8, 21, 40, 65, ...
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
This is the only set of 4-digit numbers with this property.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
'''

from generators import *

def cycle(prev, list, post):
    if len(list) == 0:
        if prev[2:] == post:
            return [prev]
        else:
            return []

    for li in list:
        index = list.index(li)
        newlist = list[:]
        del newlist[index]
        for item in li:
            if str(item)[0:2] == prev[2:]:
                temp = cycle(str(item), newlist, post)
                if len(temp) > 0:
                    return [prev] + temp

    return []

trigen = triangle()
squaregen = square()
pentgen = pentagonal()
hexgen = hexagonal()
heptgen = heptagonal()
octgen = octagonal()
digits = 4

tri = [trigen.next()]
square = [squaregen.next()]
pent = [pentgen.next()]
hex = [hexgen.next()]
hept = [heptgen.next()]
oct = [octgen.next()]
next = 0

while next < 10 ** (digits):
    next = trigen.next()
    if next > 10 ** (digits - 1) and next < 10 ** (digits):
        tri.append(next)

next = 0
while next < 10 ** (digits):
    next = squaregen.next()
    if next > 10 ** (digits - 1) and next < 10 ** (digits):
        square.append(next)

next = 0
while next < 10 ** (digits):
    next = pentgen.next()
    if next > 10 ** (digits - 1) and next < 10 ** (digits):
        pent.append(next)

next = 0
while next < 10 ** (digits):
    next = hexgen.next()
    if next > 10 ** (digits - 1) and next < 10 ** (digits):
        hex.append(next)

next = 0
while next < 10 ** (digits):
    next = heptgen.next()
    if next > 10 ** (digits - 1) and next < 10 ** (digits):
        hept.append(next)

next = 0
while next < 10 ** (digits):
    next = octgen.next()
    if next > 10 ** (digits - 1) and next < 10 ** (digits):
        oct.append(next)


for t in tri:
    temp = cycle(str(t), [square, pent, hex, hept, oct], str(t)[0:2])
    if len(temp) > 0:
        print temp
        print sumList(map(int, temp))
        break